# Generated by Django 5.1.4 on 2024-12-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='category_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
