# Generated by Django 5.1.4 on 2024-12-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_content_poster'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='content',
            name='recommender_tmdb_id_e9338d_idx',
        ),
        migrations.AlterField(
            model_name='content',
            name='stream_id',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='tmdb_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['stream_id'], name='recommender_stream__2d5d20_idx'),
        ),
    ]
