# Generated by Django 5.1.4 on 2024-12-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0004_remove_content_recommender_tmdb_id_e9338d_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(max_length=20),
        ),
    ]
